pool: 'Hosted VS2017'

variables:
  - group: subscription-info
  - name: blueprintsPath
    value: '.\blueprints\'
  - name: blueprintName
    value: 'win-main-blueprint'

steps:
- task: CreateBlueprint@1
  inputs:
    azureSubscription: $(spnName)
    BlueprintName: $(blueprintName)
    BlueprintPath: '$(blueprintsPath)$(blueprintName)'
    AlternateLocation: false
    PublishBlueprint: true
